
version: '2'

services:
  runner_stateful_client:
    user: nobody
    image: cyberdojo/runner_stateful_client
    container_name: runner_stateful_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - runner_stateful
      - runner-stateful-client-coverage-container
    volumes_from:
      - runner-stateful-client-coverage-container:rw
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_RUNNER_STATEFUL_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_RUNNER_STATEFUL_CLIENT_PORT}:${CYBER_DOJO_RUNNER_STATEFUL_CLIENT_PORT}

  runner_stateful:
    user: root
    image: cyberdojo/runner_stateful
    container_name: runner_stateful_server
    read_only: true
    tmpfs: /tmp
    depends_on:
      - runner-stateful-server-coverage-container
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    volumes_from:
      - runner-stateful-server-coverage-container:rw
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_RUNNER_STATEFUL_SERVER_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  runner-stateful-client-coverage-container:
    image: cyberdojo/runner_stateful_client
    container_name: runner-stateful-client-coverage-container
    volumes:
      - /${CYBER_DOJO_COVERAGE_ROOT}
    command: "chown nobody:nobody ${CYBER_DOJO_COVERAGE_ROOT}"


  runner-stateful-server-coverage-container:
    image: cyberdojo/runner_stateful
    container_name: runner-stateful-server-coverage-container
    volumes:
      - /${CYBER_DOJO_COVERAGE_ROOT}
